using UnityEngine;

public class GameAManager : MonoBehaviour
{
    // Referensi ke popup Canvas yang sudah dibuat di Inspector
    public GameObject canvasBerhasil;
    public GameObject canvasGagal;
    [SerializeField] private AudioSource audioSource;
    [SerializeField] private AudioClip AwardClip;

    // Flag untuk menandakan bahwa pemain sudah melakukan kesalahan
    private bool hasFailed = false;

    // Method untuk menampilkan popup berhasil
    public void ShowSuccess()
    {
        if (!hasFailed && canvasBerhasil != null)
        {
            canvasBerhasil.SetActive(true);
            if (audioSource != null && AwardClip != null)
            {
                audioSource.PlayOneShot(AwardClip);
            }
            Debug.Log("Semua sampah berhasil ditempatkan!");
        }
    }

    // Method untuk menampilkan popup gagal
    public void ShowFailure()
    {
        if (canvasGagal != null)
        {
            canvasGagal.SetActive(true);
            Debug.Log("Terdapat penempatan sampah yang salah!");
            hasFailed = true;
        }
    }
}
